
# =================
# EXPERIMENT CONFIG
# =================

script = "/tachyon/groups/scratch/gzenke/bedfrory/teacher-student/generate-teacher-activity/generate-teacher-activity.py"
output_dir = "/tachyon/groups/scratch/gzenke/bedfrory/bernstein/teacher-activity"
parameters_file = "/tachyon/groups/scratch/gzenke/bedfrory/teacher-student/generate-teacher-activity/parameters.toml"
log_file = "/tachyon/groups/scratch/gzenke/bedfrory/bernstein/Dp_simulator_log.jsonl"
description = "Generating teacher activity with Ornstein-Uhlenbeck modulation of assembly-targeted odourants for training student network"

# ===================
# WANDB CONFIGURATION
# ===================

[wandb]
enabled = false                        # Whether to use Weights & Biases for logging
project = ""                           # W&B project name
entity = ""                            # W&B entity (username or team name), leave empty to use default
tags = []                              # List of tags for organizing runs
notes = ""                             # Notes about this experiment run